' ------------------------------------------------------------
' Code generated automatically by Code Architects' VB Migration Partner
' ------------------------------------------------------------

Option Strict Off      ' Code migrated from VB6 has Option Strict disabled by default

Imports VB = Microsoft.VisualBasic

Friend Class frmDocument

	Public IsDirty As Boolean
	
	Public Sub RTF_SelChange()
	' UPGRADE_INFO (#0501): The 'RTF_SelChange' member isn't used anywhere in current application.
		' this proc simply acts as a dispatcher to the private procedure
		rtfText_SelChange()
	End Sub

	Private Sub rtfText_Change() Handles rtfText.Change
		IsDirty = True
	End Sub

	Private Sub rtfText_SelChange() Handles rtfText.SelChange
		' this is the code generated by the application wizard
		'    fMainForm.tbToolBar.Buttons("Bold").Value = IIf(rtfText.SelBold, tbrPressed, tbrUnpressed)
		'    fMainForm.tbToolBar.Buttons("Italic").Value = IIf(rtfText.SelItalic, tbrPressed, tbrUnpressed)
		'    fMainForm.tbToolBar.Buttons("Underline").Value = IIf(rtfText.SelUnderline, tbrPressed, tbrUnpressed)
		'    fMainForm.tbToolBar.Buttons("Align Left").Value = IIf(rtfText.SelAlignment = rtfLeft, tbrPressed, tbrUnpressed)
		'    fMainForm.tbToolBar.Buttons("Align Right").Value = IIf(rtfText.SelAlignment = rtfRight, tbrPressed, tbrUnpressed)
		'    fMainForm.tbToolBar.Buttons("Center").Value = IIf(rtfText.SelAlignment = rtfCenter, tbrPressed, tbrUnpressed)
		
		' keep the toolbar's button in synch with current selection
		' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelBold'. Consider using the GetDefaultMember6 helper method.
		If IsNull6(rtfText.SelBold) Then 
			fMainForm.tbToolBar.Buttons("Bold").MixedState = True
		Else
			fMainForm.tbToolBar.Buttons("Bold").MixedState = False
			' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelBold'. Consider using the GetDefaultMember6 helper method.
			fMainForm.tbToolBar.Buttons("Bold").Value = IIf(rtfText.SelBold, MSComctlLib.ValueConstants.tbrPressed, MSComctlLib.ValueConstants.tbrUnpressed)
		End If
		
		' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelItalic'. Consider using the GetDefaultMember6 helper method.
		If IsNull6(rtfText.SelItalic) Then 
			fMainForm.tbToolBar.Buttons("Italic").MixedState = True
		Else
			fMainForm.tbToolBar.Buttons("Italic").MixedState = False
			' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelItalic'. Consider using the GetDefaultMember6 helper method.
			fMainForm.tbToolBar.Buttons("Italic").Value = IIf(rtfText.SelItalic, MSComctlLib.ValueConstants.tbrPressed, MSComctlLib.ValueConstants.tbrUnpressed)
		End If
		
		' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelUnderline'. Consider using the GetDefaultMember6 helper method.
		If IsNull6(rtfText.SelUnderline) Then 
			fMainForm.tbToolBar.Buttons("Underline").MixedState = True
		Else
			fMainForm.tbToolBar.Buttons("Underline").MixedState = False
			' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelUnderline'. Consider using the GetDefaultMember6 helper method.
			fMainForm.tbToolBar.Buttons("Underline").Value = IIf(rtfText.SelUnderline, MSComctlLib.ValueConstants.tbrPressed, MSComctlLib.ValueConstants.tbrUnpressed)
		End If
		
		' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelAlignment'. Consider using the GetDefaultMember6 helper method.
		If IsNull6(rtfText.SelAlignment) Then 
			fMainForm.tbToolBar.Buttons("Align Left").MixedState = True
			fMainForm.tbToolBar.Buttons("Align Right").MixedState = True
			fMainForm.tbToolBar.Buttons("Center").MixedState = True
		Else
			fMainForm.tbToolBar.Buttons("Align Left").MixedState = False
			fMainForm.tbToolBar.Buttons("Align Right").MixedState = False
			fMainForm.tbToolBar.Buttons("Center").MixedState = False
			' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelAlignment'. Consider using the GetDefaultMember6 helper method.
			fMainForm.tbToolBar.Buttons("Align Left").Value = IIf(rtfText.SelAlignment = RichTextLib.SelAlignmentConstants.rtfLeft, MSComctlLib.ValueConstants.tbrPressed, MSComctlLib.ValueConstants.tbrUnpressed)
			' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelAlignment'. Consider using the GetDefaultMember6 helper method.
			fMainForm.tbToolBar.Buttons("Align Right").Value = IIf(rtfText.SelAlignment = RichTextLib.SelAlignmentConstants.rtfRight, MSComctlLib.ValueConstants.tbrPressed, MSComctlLib.ValueConstants.tbrUnpressed)
			' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelAlignment'. Consider using the GetDefaultMember6 helper method.
			fMainForm.tbToolBar.Buttons("Center").Value = IIf(rtfText.SelAlignment = RichTextLib.SelAlignmentConstants.rtfCenter, MSComctlLib.ValueConstants.tbrPressed, MSComctlLib.ValueConstants.tbrUnpressed)
		End If
		
		' keep the combo boxes in synch with the current selection
		If IsNull6(rtfText.SelFontName) Then 
			fMainForm.cboFonts.Text = ""
		Else
			fMainForm.cboFonts.Text = rtfText.SelFontName
		End If
		
		' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelFontSize'. Consider using the GetDefaultMember6 helper method.
		If IsNull6(rtfText.SelFontSize) Then 
			fMainForm.cboSize.Text = ""
		Else
			' UPGRADE_WARNING (#0354): Unable to read default member of symbol 'rtfText.SelFontSize'. Consider using the GetDefaultMember6 helper method.
			fMainForm.cboSize.Text = rtfText.SelFontSize
		End If
		
		' Show the current line on the status bar
		fMainForm.sbStatusBar.Panels(1).Text = "Line " & (1 + rtfText.GetLineFromChar(rtfText.SelStart))
		
	End Sub

	' this code was produced by the App Wizard
	' has been commented out because it is completely useless,
	' because the Resize event always occurs after Form_Load
	'Private Sub Form_Load()
	'    Form_Resize
	'End Sub
	
	Private Sub Form_Resize() Handles MyBase.Resize
		On Error Resume Next 
		rtfText.Move(0, 0, Me.ScaleWidth, Me.ScaleHeight)
		rtfText.RightMargin = rtfText.Width
	End Sub

	Private Sub Form_QueryUnload(ByRef Cancel As Short, ByRef UnloadMode As Short) Handles MyBase.QueryUnload
		
		If IsDirty Then 
			Select Case MsgBox6("The text in " & Caption & " has been modified." & ControlChars.Cr & "Do you wish to save it on disk?", MsgBoxStyle.Exclamation + MsgBoxStyle.YesNoCancel)
			Case MsgBoxResult.Yes
				If VB.Left(Caption, 8) = "Document" Then 
					With fMainForm.dlgCommonDialog
						.DialogTitle = "Save As"
						.CancelError = False
						.Filter = "All Files (*.*)|*.*|RTF Files (*.rtf)|*.rtf|Text Files (*.txt)|*.txt"
						.FilterIndex = 2
						.ShowSave()
						If Len6(.FileName) = 0 Then 
							Cancel = CShort(True)
						Else
							rtfText.SaveFile(.FileName)
							IsDirty = False
						End If
					End With
				Else
					rtfText.SaveFile(Caption)
					IsDirty = False
				End If
			Case MsgBoxResult.No
				IsDirty = False
			Case MsgBoxResult.Cancel
				Cancel = CShort(True)
			End Select
		End If
		' stop unloading all forms
		If Cancel Then  gloCancel = True
	End Sub

End Class
