VERSION 1.0 CLASS
BEGIN
  MultiUse = 0   'False
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Routines"
Attribute VB_GlobalNameSpace = True
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Sub NoArgs()
    '
End Sub

Sub ByRefArg(x As Long)
    '
End Sub

Sub ByValArg(ByVal x As Long)
    '
End Sub

Sub ByRefString(x As String)
    '
End Sub

Sub ByValString(ByVal x As String)
    '
End Sub




